

services:
  pygeoapi:
    build: .

    container_name: pygeoapi_processes

    ports:
      - 5000:80

    volumes:
      - ./pygeoapi.config.yml:/pygeoapi/local.config.yml
      - ./data:/data
      - ./plugins/process/squared.py:/pygeoapi/pygeoapi/process/squared.py
      - ./plugins/process/localoutlier.py:/pygeoapi/pygeoapi/process/localoutlier.py
      - ./plugins/process/geom_details.py:/pygeoapi/pygeoapi/process/geom_details.py
      - ./plugins/process/shapely_functions.py:/pygeoapi/pygeoapi/process/shapely_functions.py
